theme: jekyll-theme-minimal

title: Voyager Foundation
description: To take humanity's greatest problems and empower people to collaborate towards solutions and a brighter future.

show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

sass:
    sass_dir: _sass
    style: compressed